{
    'name': "Challan Printing",
    'description': "",
    'category': 'customization',
    'author' : 'Hamza Naveed | Odolution',
    'sequence': -10,
    'version': '1.0',
    'depends': [ 'mail', 'base', 'ol_school_manager', 'account' ], 
    'data': [
        'security/ir.model.access.csv',
        'views/challan_printing.xml',
        'views/menu_items.xml',
    ],
    'demo' : [] ,
    'qweb' : [],
    'installable' : True, 
    'application' : True,
    'auto_install' : False,
    'license': 'LGPL-3',
}